# Generated by Django 5.1.3 on 2025-10-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name=''),
        ),
    ]
